import { useEffect, useState } from 'react';
import type { IdentityManifest } from '../../shared/identity-manifest';

export function IdentityForm({ onDone, onCancel, initial }: { onDone(): void; onCancel(): void; initial?: IdentityManifest }) {
  const [label, setLabel] = useState(initial?.accountLabel ?? ''); const [id, setId] = useState(initial?.identityId ?? ''); const [chrome, setChrome] = useState(initial?.browser.executablePath ?? ''); const [profile, setProfile] = useState(initial?.browser.userDataDir ?? ''); const [protocol, setProtocol] = useState(initial?.proxy.protocol ?? 'http'); const [host, setHost] = useState(initial?.proxy.host ?? '127.0.0.1'); const [port, setPort] = useState(initial ? String(initial.proxy.port) : ''); const [locale, setLocale] = useState(initial?.environment.locale ?? 'zh-CN'); const [timezone, setTimezone] = useState(initial?.environment.timezone ?? 'Asia/Shanghai'); const [idTouched, setIdTouched] = useState(Boolean(initial)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (initial) return; void window.identityConsole.discover().then((result) => { const data = result.data as { chrome?: { recommended?: string }; proxies?: Array<{ protocol?: 'http' | 'https' | 'socks5'; host: string; port: number }> ; identityRoot?: string } | undefined; if (!result.ok || !data) return; setChrome((value) => value || data.chrome?.recommended || ''); const proxy = data.proxies?.[0]; if (proxy) { setHost((value) => value || proxy.host); setPort((value) => value || String(proxy.port)); setProtocol(proxy.protocol ?? 'http'); } }); }, [initial]);
  const suggest = (value: string): void => { setLabel(value); if (!idTouched) setId(value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')); };
  const save = async (): Promise<void> => { setSaving(true); setError(''); try { const now = new Date().toISOString(); const manifest: IdentityManifest = { ...(initial ?? {} as IdentityManifest), schemaVersion: 1, identityId: id, workspaceId: initial?.workspaceId ?? 'kv-browser-bridge', platform: initial?.platform ?? 'local', accountLabel: label, mode: initial?.mode ?? 'native-stable', browser: { executablePath: chrome, userDataDir: profile }, environment: { ...(initial?.environment ?? {}), osFamily: 'windows', locale, timezone, screen: initial?.environment.screen ?? { width: 1440, height: 900, deviceScaleFactor: 1 } }, proxy: { ...(initial?.proxy ?? {}), id: initial?.proxy.id ?? `${id}-proxy`, protocol, host, port: Number(port), authMode: initial?.proxy.authMode ?? 'none', countryCode: initial?.proxy.countryCode ?? 'CN', locale, timezone }, policies: initial?.policies ?? { webrtc: 'proxy-only', dns: 'proxy', ipv6: 'disabled', allowConcurrentSessions: false }, createdAt: initial?.createdAt ?? now, updatedAt: now }; const result = initial ? await window.identityConsole.update(manifest) : await window.identityConsole.create(manifest); if (!result.ok) { setError(`${result.error?.code ?? 'SAVE_FAILED'}: ${result.error?.message ?? ''}`); return; } onDone(); } catch (reason) { setError(`SAVE_FAILED: ${reason instanceof Error ? reason.message : String(reason)}`); } finally { setSaving(false); } };
  return <div className="identity-console"><div className="identity-console__header"><button className="identity-console__back" onClick={onCancel}>Back</button><div><div className="home__label">KV BROWSER BRIDGE</div><h1 className="identity-console__title">{initial ? 'Edit Identity' : 'New Identity'}</h1></div></div><div className="identity-card" style={{ maxWidth: 680, margin: '0 auto' }}><div className="identity-card__facts"><label><dt>Account label</dt><input value={label} onChange={(e) => suggest(e.target.value)} /></label><label><dt>Identity ID</dt><input value={id} readOnly={Boolean(initial)} onChange={(e) => { setIdTouched(true); setId(e.target.value); }} /></label><label><dt>Chrome path</dt><input value={chrome} onChange={(e) => setChrome(e.target.value)} /></label><label><dt>Profile path</dt><input value={profile} onChange={(e) => setProfile(e.target.value)} /></label><label><dt>Proxy protocol</dt><select value={protocol} onChange={(e) => setProtocol(e.target.value as typeof protocol)}><option value="http">http</option><option value="https">https</option><option value="socks5">socks5</option></select></label><label><dt>Proxy host</dt><input value={host} onChange={(e) => setHost(e.target.value)} /></label><label><dt>Proxy port</dt><input type="number" value={port} onChange={(e) => setPort(e.target.value)} /></label><label><dt>Locale</dt><input value={locale} onChange={(e) => setLocale(e.target.value)} /></label><label><dt>Timezone</dt><input value={timezone} onChange={(e) => setTimezone(e.target.value)} /></label></div>{error && <div className="identity-console__error">{error}</div>}<div className="identity-card__actions"><button disabled={saving || !label || !id || !chrome || !profile || !port} onClick={() => void save()}>{saving ? 'Saving...' : initial ? 'Save changes' : 'Create identity'}</button><button onClick={onCancel}>Cancel</button></div></div></div>;
}
