import { useEffect, useState } from 'react';
import type { IdentityManifest } from '../../../../chrome-bridge/src/identity/model';

export function IdentityForm({ onDone, onCancel }: { onDone(): void; onCancel(): void }) {
  const [label, setLabel] = useState(''); const [id, setId] = useState(''); const [chrome, setChrome] = useState(''); const [profile, setProfile] = useState(''); const [host, setHost] = useState('127.0.0.1'); const [port, setPort] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { void window.identityConsole.discover().then((result) => { const data = result.data as { chrome?: { recommended?: string }; proxies?: Array<{ host: string; port: number }> ; identityRoot?: string } | undefined; if (!data) return; setChrome(data.chrome?.recommended ?? ''); const proxy = data.proxies?.[0]; if (proxy) { setHost(proxy.host); setPort(String(proxy.port)); } }); }, []);
  const suggest = (value: string): void => { setLabel(value); const next = value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); setId(next); };
  const save = async (): Promise<void> => { setSaving(true); setError(''); const now = new Date().toISOString(); const manifest: IdentityManifest = { schemaVersion: 1, identityId: id, workspaceId: 'kv-browser-bridge', platform: 'local', accountLabel: label, mode: 'native-stable', browser: { executablePath: chrome, userDataDir: profile }, environment: { osFamily: 'windows', locale: 'zh-CN', timezone: 'Asia/Shanghai', screen: { width: 1440, height: 900, deviceScaleFactor: 1 } }, proxy: { id: `${id}-proxy`, protocol: 'http', host, port: Number(port), authMode: 'none', countryCode: 'CN', locale: 'zh-CN', timezone: 'Asia/Shanghai' }, policies: { webrtc: 'proxy-only', dns: 'proxy', ipv6: 'disabled', allowConcurrentSessions: false }, createdAt: now, updatedAt: now }; const result = await window.identityConsole.create(manifest); setSaving(false); if (!result.ok) { setError(`${result.error?.code ?? 'SAVE_FAILED'}: ${result.error?.message ?? ''}`); return; } onDone(); };
  return <div className="identity-console"><div className="identity-console__header"><button className="identity-console__back" onClick={onCancel}>Back</button><div><div className="home__label">KV BROWSER BRIDGE</div><h1 className="identity-console__title">New Identity</h1><p className="identity-console__subtitle">Create an isolated Chrome profile.</p></div></div><div className="identity-card" style={{ maxWidth: 680, margin: '0 auto' }}><div className="identity-card__facts">{[['Account label', label, suggest], ['Identity ID', id, setId], ['Chrome path', chrome, setChrome], ['Profile path', profile, setProfile], ['Proxy host', host, setHost], ['Proxy port', port, setPort]].map(([name, value, change]) => <label key={name as string}><dt>{name as string}</dt><input value={value as string} onChange={(e) => (change as (value: string) => void)(e.target.value)} /></label>)}</div>{error && <div className="identity-console__error">{error}</div>}<div className="identity-card__actions"><button disabled={saving || !label || !id || !chrome || !profile || !port} onClick={() => void save()}>{saving ? 'Saving...' : 'Create identity'}</button><button onClick={onCancel}>Cancel</button></div></div></div>;
}
